export interface FoodItem {
  name: string;
  category: string;
  servingSize: string;
  calories: number;
  protein: number; // grams
  carbs: number; // grams
  fat: number; // grams
  fiber: number; // grams
  isBangladeshi: boolean;
}

// Nutrition values are researched averages (USDA / FatSecret / Nutritionix / regional
// food-composition data) for typical home or restaurant preparations in Bangladesh.
// Real-world values vary by recipe, oil quantity, and portion — use as estimates.

export const foods: FoodItem[] = [
  // ============ Rice & Grains ============
  { name: "Rice (White, cooked)", category: "rice_grains", servingSize: "1 plate (250g)", calories: 325, protein: 6.5, carbs: 71, fat: 0.7, fiber: 0.6, isBangladeshi: true },
  { name: "Polao", category: "rice_grains", servingSize: "1 plate (250g)", calories: 450, protein: 9, carbs: 68, fat: 15, fiber: 1.2, isBangladeshi: true },
  { name: "Khichuri", category: "rice_grains", servingSize: "1 plate (300g)", calories: 380, protein: 12, carbs: 58, fat: 10, fiber: 4, isBangladeshi: true },
  { name: "Bhuna Khichuri", category: "rice_grains", servingSize: "1 plate (300g)", calories: 420, protein: 11, carbs: 60, fat: 14, fiber: 3.5, isBangladeshi: true },
  { name: "Morog Polao", category: "rice_grains", servingSize: "1 plate (350g)", calories: 580, protein: 25, carbs: 65, fat: 22, fiber: 1.5, isBangladeshi: true },
  { name: "Kacchi Biryani", category: "rice_grains", servingSize: "1 plate (400g)", calories: 720, protein: 30, carbs: 72, fat: 32, fiber: 2, isBangladeshi: true },
  { name: "Tehari", category: "rice_grains", servingSize: "1 plate (300g)", calories: 520, protein: 18, carbs: 62, fat: 20, fiber: 1.5, isBangladeshi: true },
  { name: "Chirar Polao (Flattened Rice Pilaf)", category: "rice_grains", servingSize: "1 plate (200g)", calories: 340, protein: 6, carbs: 55, fat: 11, fiber: 1.5, isBangladeshi: true },
  { name: "Brown Rice (cooked)", category: "rice_grains", servingSize: "1 plate (250g)", calories: 280, protein: 6, carbs: 58, fat: 2.5, fiber: 4.5, isBangladeshi: false },
  { name: "Oats", category: "rice_grains", servingSize: "1 cup (80g)", calories: 307, protein: 11, carbs: 55, fat: 5.3, fiber: 8, isBangladeshi: false },
  { name: "Chicken Biryani", category: "rice_grains", servingSize: "1 plate (350g)", calories: 610, protein: 28, carbs: 68, fat: 24, fiber: 1.8, isBangladeshi: true },
  { name: "Beef Tehari", category: "rice_grains", servingSize: "1 plate (350g)", calories: 590, protein: 22, carbs: 65, fat: 26, fiber: 1.5, isBangladeshi: true },
  { name: "Mutton Kacchi Biryani", category: "rice_grains", servingSize: "1 plate (400g)", calories: 750, protein: 32, carbs: 70, fat: 36, fiber: 2, isBangladeshi: true },
  { name: "Khichuri (Patla / Soft Dal-Rice)", category: "rice_grains", servingSize: "1 bowl (250g)", calories: 290, protein: 9, carbs: 48, fat: 6, fiber: 3.5, isBangladeshi: true },
  { name: "Panta Ilish (Fermented Rice with Fried Hilsa)", category: "rice_grains", servingSize: "1 serving (350g)", calories: 520, protein: 26, carbs: 60, fat: 18, fiber: 1, isBangladeshi: true },
  { name: "White Rice (cooked, 1 cup)", category: "rice_grains", servingSize: "1 cup (150g)", calories: 195, protein: 3.9, carbs: 42.5, fat: 0.4, fiber: 0.4, isBangladeshi: true },
  { name: "Quinoa (cooked)", category: "rice_grains", servingSize: "1 cup (185g)", calories: 222, protein: 8.1, carbs: 39, fat: 3.6, fiber: 5.2, isBangladeshi: false },
  { name: "Basmati Rice (cooked)", category: "rice_grains", servingSize: "1 plate (250g)", calories: 300, protein: 6, carbs: 65, fat: 0.6, fiber: 1, isBangladeshi: false },
  { name: "Fried Rice (Egg & Veg)", category: "rice_grains", servingSize: "1 plate (300g)", calories: 460, protein: 12, carbs: 62, fat: 18, fiber: 2.5, isBangladeshi: false },

  // ============ Curry & Meat ============
  { name: "Dal (Lentil Soup)", category: "curry_meat", servingSize: "1 bowl (200ml)", calories: 180, protein: 12, carbs: 28, fat: 3, fiber: 8, isBangladeshi: true },
  { name: "Chicken Curry", category: "curry_meat", servingSize: "1 serving (200g)", calories: 320, protein: 28, carbs: 8, fat: 20, fiber: 1, isBangladeshi: true },
  { name: "Chicken Bhuna", category: "curry_meat", servingSize: "1 serving (150g)", calories: 280, protein: 24, carbs: 6, fat: 18, fiber: 0.5, isBangladeshi: true },
  { name: "Beef Curry", category: "curry_meat", servingSize: "1 serving (200g)", calories: 380, protein: 32, carbs: 6, fat: 26, fiber: 0.5, isBangladeshi: true },
  { name: "Beef Bhuna", category: "curry_meat", servingSize: "1 serving (150g)", calories: 340, protein: 26, carbs: 5, fat: 24, fiber: 0.5, isBangladeshi: true },
  { name: "Kala Bhuna", category: "curry_meat", servingSize: "1 serving (150g)", calories: 380, protein: 28, carbs: 5, fat: 28, fiber: 0.5, isBangladeshi: true },
  { name: "Mutton Curry (Khashir Mangsho)", category: "curry_meat", servingSize: "1 serving (200g)", calories: 420, protein: 30, carbs: 6, fat: 32, fiber: 0.5, isBangladeshi: true },
  { name: "Chicken Grill", category: "curry_meat", servingSize: "1 piece (150g)", calories: 250, protein: 38, carbs: 2, fat: 10, fiber: 0, isBangladeshi: true },
  { name: "Chicken Roast", category: "curry_meat", servingSize: "1 piece (150g)", calories: 280, protein: 35, carbs: 5, fat: 14, fiber: 0.5, isBangladeshi: true },
  { name: "Egg Curry (Dim Bhuna)", category: "curry_meat", servingSize: "1 serving, 2 eggs (150g)", calories: 260, protein: 14, carbs: 6, fat: 20, fiber: 0.5, isBangladeshi: true },
  { name: "Chickpeas (Chole)", category: "curry_meat", servingSize: "1 bowl (150g)", calories: 210, protein: 11, carbs: 33, fat: 4, fiber: 9, isBangladeshi: true },
  { name: "Mixed Vegetable Curry (Shobji Bhaji)", category: "curry_meat", servingSize: "1 bowl (150g)", calories: 140, protein: 3, carbs: 15, fat: 8, fiber: 4, isBangladeshi: true },
  { name: "Aloo Bhorta (Mashed Potato)", category: "curry_meat", servingSize: "1 serving (100g)", calories: 140, protein: 2, carbs: 20, fat: 6, fiber: 2, isBangladeshi: true },
  { name: "Begun Bhaja (Fried Eggplant)", category: "curry_meat", servingSize: "1 serving (100g)", calories: 150, protein: 1.5, carbs: 10, fat: 12, fiber: 3, isBangladeshi: true },
  { name: "Shutki Bhuna (Dried Fish Curry)", category: "curry_meat", servingSize: "1 serving (100g)", calories: 220, protein: 20, carbs: 4, fat: 14, fiber: 0.5, isBangladeshi: true },
  { name: "Chicken Korma", category: "curry_meat", servingSize: "1 serving (200g)", calories: 360, protein: 25, carbs: 12, fat: 24, fiber: 1, isBangladeshi: true },
  { name: "Beef Rezala", category: "curry_meat", servingSize: "1 serving (200g)", calories: 410, protein: 30, carbs: 8, fat: 28, fiber: 0.5, isBangladeshi: true },
  { name: "Shami Kabab (Beef)", category: "curry_meat", servingSize: "1 piece (60g)", calories: 140, protein: 11, carbs: 6, fat: 8, fiber: 1, isBangladeshi: true },
  { name: "Chicken Seekh Kabab", category: "curry_meat", servingSize: "1 skewer (80g)", calories: 160, protein: 18, carbs: 3, fat: 8, fiber: 0.5, isBangladeshi: true },
  { name: "Beef Liver Curry (Kolija Bhuna)", category: "curry_meat", servingSize: "1 serving (150g)", calories: 260, protein: 27, carbs: 6, fat: 14, fiber: 0.5, isBangladeshi: true },
  { name: "Duck Curry (Hansher Mangsho)", category: "curry_meat", servingSize: "1 serving (200g)", calories: 440, protein: 26, carbs: 6, fat: 34, fiber: 0.5, isBangladeshi: true },
  { name: "Lau Chingri (Bottle Gourd with Shrimp)", category: "curry_meat", servingSize: "1 bowl (200g)", calories: 160, protein: 12, carbs: 10, fat: 8, fiber: 3, isBangladeshi: true },
  { name: "Chicken Breast (Grilled)", category: "curry_meat", servingSize: "1 piece (120g)", calories: 198, protein: 37, carbs: 0, fat: 4.3, fiber: 0, isBangladeshi: false },
  { name: "Palak Paneer", category: "curry_meat", servingSize: "1 bowl (200g)", calories: 270, protein: 14, carbs: 10, fat: 19, fiber: 3.5, isBangladeshi: false },
  { name: "Beef Steak (Grilled)", category: "curry_meat", servingSize: "1 piece (200g)", calories: 450, protein: 50, carbs: 0, fat: 28, fiber: 0, isBangladeshi: false },
  { name: "Fish Bhorta (Takla/Rui)", category: "curry_meat", servingSize: "1 serving (80g)", calories: 130, protein: 14, carbs: 4, fat: 6, fiber: 1, isBangladeshi: true },

  // ============ Fish & Seafood ============
  { name: "Fish Curry (Ilish)", category: "fish_seafood", servingSize: "1 piece (120g)", calories: 280, protein: 22, carbs: 4, fat: 20, fiber: 0.5, isBangladeshi: true },
  { name: "Shorshe Ilish (Hilsa in Mustard Sauce)", category: "fish_seafood", servingSize: "1 piece (120g)", calories: 300, protein: 20, carbs: 5, fat: 23, fiber: 1, isBangladeshi: true },
  { name: "Fish (Rohu, fried)", category: "fish_seafood", servingSize: "1 piece (100g)", calories: 220, protein: 24, carbs: 5, fat: 12, fiber: 0, isBangladeshi: true },
  { name: "Fish Fry (Pangas/Tilapia)", category: "fish_seafood", servingSize: "1 piece (100g)", calories: 210, protein: 20, carbs: 5, fat: 12, fiber: 0, isBangladeshi: true },
  { name: "Chingri Malai Curry (Shrimp in Coconut Milk)", category: "fish_seafood", servingSize: "1 serving (200g)", calories: 320, protein: 22, carbs: 8, fat: 22, fiber: 1, isBangladeshi: true },
  { name: "Chingri Bhuna (Shrimp Curry)", category: "fish_seafood", servingSize: "1 serving (150g)", calories: 230, protein: 20, carbs: 6, fat: 14, fiber: 0.5, isBangladeshi: true },
  { name: "Shutki Maach (Fried Dried Fish)", category: "fish_seafood", servingSize: "1 serving (50g)", calories: 160, protein: 18, carbs: 2, fat: 9, fiber: 0, isBangladeshi: true },
  { name: "Fish Curry (Rui / Katla)", category: "fish_seafood", servingSize: "1 piece with gravy (150g)", calories: 240, protein: 22, carbs: 5, fat: 14, fiber: 0.5, isBangladeshi: true },
  { name: "Shorshe Pabda (Pabda Fish in Mustard Curry)", category: "fish_seafood", servingSize: "1 piece (120g)", calories: 230, protein: 18, carbs: 4, fat: 15, fiber: 0.5, isBangladeshi: true },
  { name: "Boal Fish Curry", category: "fish_seafood", servingSize: "1 piece (150g)", calories: 270, protein: 24, carbs: 5, fat: 17, fiber: 0.5, isBangladeshi: true },
  { name: "Crab Curry (Kankra Bhuna)", category: "fish_seafood", servingSize: "1 serving (150g)", calories: 190, protein: 21, carbs: 5, fat: 9, fiber: 0.5, isBangladeshi: true },
  { name: "Salmon (Baked/Grilled)", category: "fish_seafood", servingSize: "1 piece (150g)", calories: 310, protein: 34, carbs: 0, fat: 18, fiber: 0, isBangladeshi: false },
  { name: "Canned Tuna (in water, drained)", category: "fish_seafood", servingSize: "1 can (112g)", calories: 120, protein: 26, carbs: 0, fat: 1, fiber: 0, isBangladeshi: false },
  { name: "Shrimp Fry (Crispy)", category: "fish_seafood", servingSize: "1 serving (100g)", calories: 220, protein: 20, carbs: 8, fat: 12, fiber: 0.5, isBangladeshi: true },

  // ============ Bread & Bakery ============
  { name: "Naan", category: "bread_bakery", servingSize: "1 piece (90g)", calories: 260, protein: 8, carbs: 45, fat: 5, fiber: 2, isBangladeshi: true },
  { name: "Paratha", category: "bread_bakery", servingSize: "1 piece (80g)", calories: 280, protein: 5, carbs: 36, fat: 13, fiber: 1.5, isBangladeshi: true },
  { name: "Roti", category: "bread_bakery", servingSize: "1 piece (40g)", calories: 104, protein: 3, carbs: 18, fat: 3, fiber: 2, isBangladeshi: true },
  { name: "Luchi (Fried Flatbread)", category: "bread_bakery", servingSize: "1 piece (30g)", calories: 110, protein: 2, carbs: 12, fat: 6, fiber: 0.5, isBangladeshi: true },
  { name: "Bakarkhani", category: "bread_bakery", servingSize: "1 piece (60g)", calories: 250, protein: 5, carbs: 32, fat: 11, fiber: 1, isBangladeshi: true },
  { name: "Rumali Roti", category: "bread_bakery", servingSize: "1 piece (60g)", calories: 170, protein: 5, carbs: 32, fat: 2.5, fiber: 1.5, isBangladeshi: true },
  { name: "Tandoori Roti", category: "bread_bakery", servingSize: "1 piece (50g)", calories: 125, protein: 4, carbs: 25, fat: 1, fiber: 2, isBangladeshi: true },
  { name: "Garlic Naan", category: "bread_bakery", servingSize: "1 piece (100g)", calories: 310, protein: 9, carbs: 50, fat: 8, fiber: 2, isBangladeshi: true },
  { name: "Milk Bread Slice", category: "bread_bakery", servingSize: "1 slice (30g)", calories: 80, protein: 2.5, carbs: 14, fat: 1.2, fiber: 0.6, isBangladeshi: true },
  { name: "Brown Whole Wheat Bread", category: "bread_bakery", servingSize: "1 slice (35g)", calories: 85, protein: 3.5, carbs: 14, fat: 1.2, fiber: 2, isBangladeshi: false },
  { name: "Lachha Paratha", category: "bread_bakery", servingSize: "1 piece (100g)", calories: 340, protein: 6, carbs: 42, fat: 16, fiber: 2, isBangladeshi: true },
  { name: "Aloo Paratha", category: "bread_bakery", servingSize: "1 piece (120g)", calories: 310, protein: 6, carbs: 48, fat: 11, fiber: 3, isBangladeshi: true },

  // ============ Dairy & Eggs ============
  { name: "Egg (Whole, boiled)", category: "dairy_eggs", servingSize: "1 large", calories: 78, protein: 6, carbs: 0.6, fat: 5, fiber: 0, isBangladeshi: true },
  { name: "Boiled Egg White", category: "dairy_eggs", servingSize: "1 large", calories: 17, protein: 3.6, carbs: 0.2, fat: 0.1, fiber: 0, isBangladeshi: false },
  { name: "Sweet Yogurt (Mishti Doi)", category: "dairy_eggs", servingSize: "1 cup (150g)", calories: 180, protein: 5, carbs: 30, fat: 5, fiber: 0, isBangladeshi: true },
  { name: "Plain Yogurt", category: "dairy_eggs", servingSize: "1 cup (150g)", calories: 95, protein: 8, carbs: 11, fat: 2, fiber: 0, isBangladeshi: true },
  { name: "Milk (Whole)", category: "dairy_eggs", servingSize: "1 glass (250ml)", calories: 150, protein: 8, carbs: 12, fat: 8, fiber: 0, isBangladeshi: true },
  { name: "Paneer/Chana (Fresh Cheese)", category: "dairy_eggs", servingSize: "100g", calories: 265, protein: 18, carbs: 6, fat: 20, fiber: 0, isBangladeshi: true },
  { name: "Egg Omelette (2 eggs with oil & onion)", category: "dairy_eggs", servingSize: "1 serving (120g)", calories: 210, protein: 13, carbs: 3, fat: 16, fiber: 0.5, isBangladeshi: true },
  { name: "Egg Poached", category: "dairy_eggs", servingSize: "1 large", calories: 72, protein: 6.3, carbs: 0.4, fat: 4.7, fiber: 0, isBangladeshi: false },
  { name: "Curd / Laban (Unsweetened)", category: "dairy_eggs", servingSize: "1 glass (250ml)", calories: 110, protein: 7, carbs: 9, fat: 5, fiber: 0, isBangladeshi: true },
  { name: "Ghee (Clarified Butter)", category: "dairy_eggs", servingSize: "1 tbsp (14g)", calories: 123, protein: 0, carbs: 0, fat: 14, fiber: 0, isBangladeshi: true },
  { name: "Whey Protein Powder", category: "dairy_eggs", servingSize: "1 scoop (30g)", calories: 120, protein: 24, carbs: 2, fat: 1.5, fiber: 0, isBangladeshi: false },
  { name: "Cheddar Cheese", category: "dairy_eggs", servingSize: "1 slice (28g)", calories: 113, protein: 7, carbs: 0.4, fat: 9.3, fiber: 0, isBangladeshi: false },
  { name: "Butter", category: "dairy_eggs", servingSize: "1 tbsp (14g)", calories: 102, protein: 0.1, carbs: 0, fat: 11.5, fiber: 0, isBangladeshi: false },

  // ============ Fruits & Vegetables ============
  { name: "Banana", category: "fruits_veg", servingSize: "1 medium", calories: 105, protein: 1.3, carbs: 27, fat: 0.4, fiber: 3.1, isBangladeshi: false },
  { name: "Apple", category: "fruits_veg", servingSize: "1 medium", calories: 95, protein: 0.5, carbs: 25, fat: 0.3, fiber: 4.4, isBangladeshi: false },
  { name: "Mango (Aam)", category: "fruits_veg", servingSize: "1 medium (200g)", calories: 120, protein: 1.6, carbs: 30, fat: 0.6, fiber: 3.2, isBangladeshi: true },
  { name: "Jackfruit (Kathal)", category: "fruits_veg", servingSize: "1 cup, chopped (150g)", calories: 143, protein: 2, carbs: 35, fat: 0.5, fiber: 2.4, isBangladeshi: true },
  { name: "Litchi (Lichu)", category: "fruits_veg", servingSize: "10 pieces (100g)", calories: 66, protein: 0.8, carbs: 16.5, fat: 0.4, fiber: 1.3, isBangladeshi: true },
  { name: "Guava (Peyara)", category: "fruits_veg", servingSize: "1 medium (100g)", calories: 68, protein: 2.6, carbs: 14, fat: 1, fiber: 5.4, isBangladeshi: true },
  { name: "Papaya (Pepe)", category: "fruits_veg", servingSize: "1 cup, chopped (140g)", calories: 55, protein: 0.6, carbs: 14, fat: 0.2, fiber: 2.5, isBangladeshi: true },
  { name: "Pineapple (Anarosh)", category: "fruits_veg", servingSize: "1 cup, chopped (150g)", calories: 82, protein: 0.9, carbs: 22, fat: 0.2, fiber: 2.3, isBangladeshi: true },
  { name: "Jujube (Boroi)", category: "fruits_veg", servingSize: "100g", calories: 79, protein: 0.8, carbs: 20, fat: 0.2, fiber: 2.5, isBangladeshi: true },
  { name: "Watermelon (Tarmuj)", category: "fruits_veg", servingSize: "1 cup, chopped (150g)", calories: 45, protein: 0.9, carbs: 11, fat: 0.2, fiber: 0.6, isBangladeshi: true },
  { name: "Green Apple", category: "fruits_veg", servingSize: "1 medium (150g)", calories: 80, protein: 0.4, carbs: 21, fat: 0.2, fiber: 4, isBangladeshi: false },
  { name: "Orange (Komola)", category: "fruits_veg", servingSize: "1 medium (130g)", calories: 62, protein: 1.2, carbs: 15, fat: 0.2, fiber: 3.1, isBangladeshi: true },
  { name: "Pomegranate (Dalim/Anar)", category: "fruits_veg", servingSize: "1 medium (150g)", calories: 125, protein: 2.5, carbs: 28, fat: 1.8, fiber: 6, isBangladeshi: true },
  { name: "Sweet Potato (Boiled)", category: "fruits_veg", servingSize: "1 medium (130g)", calories: 112, protein: 2, carbs: 26, fat: 0.1, fiber: 3.9, isBangladeshi: true },
  { name: "Coconut Water (Dab-er Pani)", category: "fruits_veg", servingSize: "1 glass (250ml)", calories: 45, protein: 1.7, carbs: 9, fat: 0.5, fiber: 2.6, isBangladeshi: true },
  { name: "Avocado", category: "fruits_veg", servingSize: "1/2 fruit (100g)", calories: 160, protein: 2, carbs: 8.5, fat: 14.7, fiber: 6.7, isBangladeshi: false },
  { name: "Wood Apple (Bel)", category: "fruits_veg", servingSize: "100g", calories: 137, protein: 1.8, carbs: 31, fat: 0.3, fiber: 5, isBangladeshi: true },
  { name: "Hog Plum (Amra)", category: "fruits_veg", servingSize: "1 piece (80g)", calories: 48, protein: 0.8, carbs: 11, fat: 0.2, fiber: 3, isBangladeshi: true },
  { name: "Starfruit (Kamranga)", category: "fruits_veg", servingSize: "1 medium (90g)", calories: 28, protein: 0.9, carbs: 6.7, fat: 0.3, fiber: 2.5, isBangladeshi: true },
  { name: "Green Peas (Koraishuti)", category: "fruits_veg", servingSize: "1 cup (145g)", calories: 118, protein: 8.2, carbs: 21, fat: 0.6, fiber: 8.3, isBangladeshi: true },

  // ============ Snacks & Street Food ============
  { name: "Singara", category: "snacks_street", servingSize: "1 piece (50g)", calories: 155, protein: 2.5, carbs: 17, fat: 8, fiber: 1, isBangladeshi: true },
  { name: "Samosa", category: "snacks_street", servingSize: "1 piece (50g)", calories: 155, protein: 2.5, carbs: 16.5, fat: 8.5, fiber: 1, isBangladeshi: true },
  { name: "Piyaju (Lentil Fritters)", category: "snacks_street", servingSize: "1 piece (25g)", calories: 70, protein: 2.5, carbs: 6, fat: 4, fiber: 1.5, isBangladeshi: true },
  { name: "Beguni (Eggplant Fritters)", category: "snacks_street", servingSize: "1 piece (30g)", calories: 75, protein: 1, carbs: 6, fat: 5, fiber: 1, isBangladeshi: true },
  { name: "Alur Chop (Potato Fritters)", category: "snacks_street", servingSize: "1 piece (40g)", calories: 100, protein: 1.5, carbs: 12, fat: 5, fiber: 1, isBangladeshi: true },
  { name: "Fuchka (Bangladeshi Panipuri)", category: "snacks_street", servingSize: "6 pieces (150g)", calories: 180, protein: 4, carbs: 30, fat: 5, fiber: 2, isBangladeshi: true },
  { name: "Chotpoti", category: "snacks_street", servingSize: "1 bowl (200g)", calories: 250, protein: 9, carbs: 35, fat: 8, fiber: 6, isBangladeshi: true },
  { name: "Jhal Muri", category: "snacks_street", servingSize: "1 bowl (100g)", calories: 180, protein: 4, carbs: 28, fat: 6, fiber: 2, isBangladeshi: true },
  { name: "Ghugni", category: "snacks_street", servingSize: "1 bowl (150g)", calories: 150, protein: 6, carbs: 25, fat: 4.5, fiber: 5, isBangladeshi: true },
  { name: "Halim", category: "snacks_street", servingSize: "1 bowl (300g)", calories: 380, protein: 22, carbs: 35, fat: 16, fiber: 5, isBangladeshi: true },
  { name: "Dal Puri", category: "snacks_street", servingSize: "1 piece (50g)", calories: 160, protein: 4, carbs: 20, fat: 7, fiber: 2, isBangladeshi: true },
  { name: "Nimki", category: "snacks_street", servingSize: "1 serving (30g)", calories: 145, protein: 2.5, carbs: 16.5, fat: 7.5, fiber: 0.6, isBangladeshi: true },
  { name: "Dim Chop (Egg Chop)", category: "snacks_street", servingSize: "1 piece (60g)", calories: 160, protein: 6, carbs: 14, fat: 9, fiber: 1, isBangladeshi: true },
  { name: "Vegetable Chop", category: "snacks_street", servingSize: "1 piece (60g)", calories: 140, protein: 3, carbs: 18, fat: 6, fiber: 2, isBangladeshi: true },
  { name: "Papri Chaat", category: "snacks_street", servingSize: "1 plate (150g)", calories: 280, protein: 6, carbs: 38, fat: 12, fiber: 3, isBangladeshi: true },
  { name: "Bhelpuri", category: "snacks_street", servingSize: "1 plate (150g)", calories: 200, protein: 5, carbs: 35, fat: 5, fiber: 3, isBangladeshi: true },
  { name: "Churmur", category: "snacks_street", servingSize: "1 bowl (150g)", calories: 220, protein: 5, carbs: 32, fat: 8, fiber: 3, isBangladeshi: true },
  { name: "Fried Chicken (Street-style)", category: "snacks_street", servingSize: "1 piece (100g)", calories: 260, protein: 20, carbs: 12, fat: 15, fiber: 0.5, isBangladeshi: true },
  { name: "Chicken Shawarma Roll", category: "snacks_street", servingSize: "1 roll (250g)", calories: 480, protein: 28, carbs: 45, fat: 22, fiber: 2, isBangladeshi: true },
  { name: "Bun Kabab (Chicken Bun)", category: "snacks_street", servingSize: "1 piece (120g)", calories: 320, protein: 14, carbs: 38, fat: 12, fiber: 2, isBangladeshi: true },
  { name: "Aloo Puri", category: "snacks_street", servingSize: "1 serving, 2 puris + curry (150g)", calories: 320, protein: 6, carbs: 40, fat: 14, fiber: 3, isBangladeshi: true },
  { name: "Chicken Patties", category: "snacks_street", servingSize: "1 piece (80g)", calories: 240, protein: 7, carbs: 22, fat: 14, fiber: 1, isBangladeshi: true },
  { name: "Beef Patties", category: "snacks_street", servingSize: "1 piece (80g)", calories: 260, protein: 8, carbs: 22, fat: 16, fiber: 1, isBangladeshi: true },
  { name: "Vegetable Singara", category: "snacks_street", servingSize: "1 piece (50g)", calories: 145, protein: 2, carbs: 18, fat: 7, fiber: 1.5, isBangladeshi: true },
  { name: "Chicken Roll (Bakery style)", category: "snacks_street", servingSize: "1 roll (120g)", calories: 290, protein: 14, carbs: 30, fat: 13, fiber: 1.5, isBangladeshi: true },
  { name: "French Fries", category: "snacks_street", servingSize: "1 medium serving (100g)", calories: 312, protein: 3.4, carbs: 41, fat: 15, fiber: 3.8, isBangladeshi: false },
  { name: "Chicken Momos", category: "snacks_street", servingSize: "6 pieces (150g)", calories: 260, protein: 14, carbs: 36, fat: 6, fiber: 1.5, isBangladeshi: false },
  { name: "Velpuri / Fuchka with Sweet Chutney", category: "snacks_street", servingSize: "1 plate (150g)", calories: 210, protein: 4, carbs: 34, fat: 6, fiber: 2.5, isBangladeshi: true },

  // ============ Sweets & Mishti ============
  { name: "Rasgulla (Roshogolla)", category: "sweets_mishti", servingSize: "1 piece (40g)", calories: 106, protein: 2, carbs: 20, fat: 2, fiber: 0, isBangladeshi: true },
  { name: "Sandesh", category: "sweets_mishti", servingSize: "1 piece (30g)", calories: 90, protein: 3, carbs: 12, fat: 3.5, fiber: 0, isBangladeshi: true },
  { name: "Chomchom", category: "sweets_mishti", servingSize: "1 piece (50g)", calories: 150, protein: 3.5, carbs: 24, fat: 5, fiber: 0, isBangladeshi: true },
  { name: "Kalojaam (Kala Jam)", category: "sweets_mishti", servingSize: "1 piece (40g)", calories: 130, protein: 2, carbs: 18, fat: 6, fiber: 0, isBangladeshi: true },
  { name: "Jilapi (Jalebi)", category: "sweets_mishti", servingSize: "1 piece (25g)", calories: 79, protein: 0.5, carbs: 11, fat: 3.5, fiber: 0, isBangladeshi: true },
  { name: "Chanar Payesh (Rice Pudding)", category: "sweets_mishti", servingSize: "1 bowl (150g)", calories: 220, protein: 6, carbs: 34, fat: 7, fiber: 0.5, isBangladeshi: true },
  { name: "Shemai (Vermicelli Pudding)", category: "sweets_mishti", servingSize: "1 bowl (150g)", calories: 260, protein: 5, carbs: 40, fat: 9, fiber: 0.5, isBangladeshi: true },
  { name: "Bhapa Pitha", category: "sweets_mishti", servingSize: "1 piece (80g)", calories: 180, protein: 3, carbs: 30, fat: 5, fiber: 1, isBangladeshi: true },
  { name: "Chitoi Pitha", category: "sweets_mishti", servingSize: "1 piece (60g)", calories: 120, protein: 2.5, carbs: 24, fat: 1, fiber: 0.5, isBangladeshi: true },
  { name: "Gulab Jamun", category: "sweets_mishti", servingSize: "1 piece (40g)", calories: 150, protein: 2.2, carbs: 23, fat: 6, fiber: 0, isBangladeshi: true },
  { name: "Rasmalai", category: "sweets_mishti", servingSize: "2 pieces with milk (150g)", calories: 250, protein: 7, carbs: 32, fat: 10, fiber: 0, isBangladeshi: true },
  { name: "Doi Chira (Flattened Rice with Sweet Yogurt)", category: "sweets_mishti", servingSize: "1 bowl (200g)", calories: 280, protein: 7, carbs: 48, fat: 6, fiber: 1.5, isBangladeshi: true },
  { name: "Pati Sapta Pitha", category: "sweets_mishti", servingSize: "1 piece (70g)", calories: 160, protein: 3, carbs: 28, fat: 4, fiber: 0.5, isBangladeshi: true },
  { name: "Firni", category: "sweets_mishti", servingSize: "1 bowl (150g)", calories: 210, protein: 5, carbs: 32, fat: 7, fiber: 0.3, isBangladeshi: true },
  { name: "Motichoor Laddu", category: "sweets_mishti", servingSize: "1 piece (35g)", calories: 140, protein: 1.8, carbs: 20, fat: 6, fiber: 0.8, isBangladeshi: true },
  { name: "Gajar Halwa (Carrot Sweet)", category: "sweets_mishti", servingSize: "1 bowl (100g)", calories: 230, protein: 3.5, carbs: 32, fat: 10, fiber: 1.5, isBangladeshi: true },

  // ============ Beverages ============
  { name: "Borhani (Savory Yogurt Drink)", category: "beverages", servingSize: "1 glass (250ml)", calories: 120, protein: 4, carbs: 12, fat: 6, fiber: 0, isBangladeshi: true },
  { name: "Lassi (Sweet)", category: "beverages", servingSize: "1 glass (250ml)", calories: 220, protein: 6, carbs: 32, fat: 7, fiber: 0, isBangladeshi: true },
  { name: "Cha (Milk Tea, sweetened)", category: "beverages", servingSize: "1 cup (150ml)", calories: 60, protein: 1.5, carbs: 10, fat: 1.5, fiber: 0, isBangladeshi: true },
  { name: "Lebur Sharbat (Lemon Drink)", category: "beverages", servingSize: "1 glass (250ml)", calories: 90, protein: 0.2, carbs: 23, fat: 0, fiber: 0.2, isBangladeshi: true },
  { name: "Tetuler Sharbat (Tamarind Drink)", category: "beverages", servingSize: "1 glass (250ml)", calories: 110, protein: 0.3, carbs: 28, fat: 0, fiber: 0.5, isBangladeshi: true },
  { name: "Black Tea (Lal Cha, unsweetened)", category: "beverages", servingSize: "1 cup (150ml)", calories: 2, protein: 0.1, carbs: 0.4, fat: 0, fiber: 0, isBangladeshi: true },
  { name: "Black Coffee (Unsweetened)", category: "beverages", servingSize: "1 cup (200ml)", calories: 2, protein: 0.3, carbs: 0, fat: 0, fiber: 0, isBangladeshi: false },
  { name: "Cold Coffee (Sweetened)", category: "beverages", servingSize: "1 glass (250ml)", calories: 180, protein: 5, carbs: 26, fat: 6, fiber: 0, isBangladeshi: true },
  { name: "Mango Juice", category: "beverages", servingSize: "1 glass (250ml)", calories: 135, protein: 0.8, carbs: 34, fat: 0.3, fiber: 1, isBangladeshi: true },
  { name: "Sugarcane Juice (Akher Ras)", category: "beverages", servingSize: "1 glass (250ml)", calories: 180, protein: 0.5, carbs: 45, fat: 0, fiber: 0.5, isBangladeshi: true },
  { name: "Matha (Traditional Buttermilk)", category: "beverages", servingSize: "1 glass (250ml)", calories: 95, protein: 4, carbs: 10, fat: 4, fiber: 0, isBangladeshi: true },

  // ============ Single/Dry Foods — multi-portion (15g / 25g / 50g / 100g) ============
  { name: "Muri (Puffed Rice)", category: "snacks_dry", servingSize: "15g", calories: 56, protein: 1.1, carbs: 12.3, fat: 0.1, fiber: 0.2, isBangladeshi: true },
  { name: "Muri (Puffed Rice)", category: "snacks_dry", servingSize: "25g", calories: 93, protein: 1.8, carbs: 20.5, fat: 0.1, fiber: 0.4, isBangladeshi: true },
  { name: "Muri (Puffed Rice)", category: "snacks_dry", servingSize: "50g", calories: 185, protein: 3.5, carbs: 41, fat: 0.3, fiber: 0.7, isBangladeshi: true },
  { name: "Muri (Puffed Rice)", category: "snacks_dry", servingSize: "100g", calories: 370, protein: 7, carbs: 82, fat: 0.5, fiber: 1.4, isBangladeshi: true },
  { name: "Chira (Flattened Rice, raw)", category: "snacks_dry", servingSize: "15g", calories: 53, protein: 1, carbs: 11.5, fat: 0.2, fiber: 0.2, isBangladeshi: true },
  { name: "Chira (Flattened Rice, raw)", category: "snacks_dry", servingSize: "25g", calories: 89, protein: 1.7, carbs: 19.2, fat: 0.3, fiber: 0.4, isBangladeshi: true },
  { name: "Chira (Flattened Rice, raw)", category: "snacks_dry", servingSize: "50g", calories: 178, protein: 3.3, carbs: 38.5, fat: 0.6, fiber: 0.8, isBangladeshi: true },
  { name: "Chira (Flattened Rice, raw)", category: "snacks_dry", servingSize: "100g", calories: 356, protein: 6.6, carbs: 76.9, fat: 1.2, fiber: 1.5, isBangladeshi: true },
  { name: "Chanachur (Bombay Mix)", category: "snacks_dry", servingSize: "15g", calories: 72, protein: 1.8, carbs: 6.8, fat: 4.2, fiber: 0.8, isBangladeshi: true },
  { name: "Chanachur (Bombay Mix)", category: "snacks_dry", servingSize: "25g", calories: 120, protein: 3, carbs: 11.3, fat: 7, fiber: 1.3, isBangladeshi: true },
  { name: "Chanachur (Bombay Mix)", category: "snacks_dry", servingSize: "50g", calories: 240, protein: 6, carbs: 22.5, fat: 14, fiber: 2.5, isBangladeshi: true },
  { name: "Chanachur (Bombay Mix)", category: "snacks_dry", servingSize: "100g", calories: 480, protein: 12, carbs: 45, fat: 28, fiber: 5, isBangladeshi: true },
  { name: "Peanuts (Chinabadam, roasted)", category: "snacks_dry", servingSize: "15g", calories: 86, protein: 3.8, carbs: 2.4, fat: 7.2, fiber: 1.2, isBangladeshi: true },
  { name: "Peanuts (Chinabadam, roasted)", category: "snacks_dry", servingSize: "25g", calories: 143, protein: 6.3, carbs: 4, fat: 12, fiber: 2, isBangladeshi: true },
  { name: "Peanuts (Chinabadam, roasted)", category: "snacks_dry", servingSize: "50g", calories: 285, protein: 12.5, carbs: 8, fat: 24, fiber: 4, isBangladeshi: true },
  { name: "Peanuts (Chinabadam, roasted)", category: "snacks_dry", servingSize: "100g", calories: 570, protein: 25, carbs: 16, fat: 48, fiber: 8, isBangladeshi: true },
  { name: "Roasted Chickpeas (Bhaja Chola)", category: "snacks_dry", servingSize: "15g", calories: 57, protein: 3, carbs: 9, fat: 0.9, fiber: 2.6, isBangladeshi: true },
  { name: "Roasted Chickpeas (Bhaja Chola)", category: "snacks_dry", servingSize: "25g", calories: 95, protein: 5, carbs: 15, fat: 1.5, fiber: 4.3, isBangladeshi: true },
  { name: "Roasted Chickpeas (Bhaja Chola)", category: "snacks_dry", servingSize: "50g", calories: 190, protein: 10, carbs: 30, fat: 3, fiber: 8.5, isBangladeshi: true },
  { name: "Roasted Chickpeas (Bhaja Chola)", category: "snacks_dry", servingSize: "100g", calories: 380, protein: 20, carbs: 60, fat: 6, fiber: 17, isBangladeshi: true },
  { name: "Coconut (Narikel, fresh grated)", category: "snacks_dry", servingSize: "15g", calories: 53, protein: 0.5, carbs: 2.3, fat: 5, fiber: 1.3, isBangladeshi: true },
  { name: "Coconut (Narikel, fresh grated)", category: "snacks_dry", servingSize: "25g", calories: 89, protein: 0.8, carbs: 3.8, fat: 8.4, fiber: 2.3, isBangladeshi: true },
  { name: "Coconut (Narikel, fresh grated)", category: "snacks_dry", servingSize: "50g", calories: 177, protein: 1.7, carbs: 7.6, fat: 16.8, fiber: 4.5, isBangladeshi: true },
  { name: "Coconut (Narikel, fresh grated)", category: "snacks_dry", servingSize: "100g", calories: 354, protein: 3.3, carbs: 15.2, fat: 33.5, fiber: 9, isBangladeshi: true },
  { name: "Dates (Khejur)", category: "snacks_dry", servingSize: "15g", calories: 42, protein: 0.3, carbs: 11.3, fat: 0, fiber: 1, isBangladeshi: true },
  { name: "Dates (Khejur)", category: "snacks_dry", servingSize: "25g", calories: 69, protein: 0.5, carbs: 18.8, fat: 0.1, fiber: 1.7, isBangladeshi: true },
  { name: "Dates (Khejur)", category: "snacks_dry", servingSize: "50g", calories: 139, protein: 0.9, carbs: 37.5, fat: 0.1, fiber: 3.4, isBangladeshi: true },
  { name: "Dates (Khejur)", category: "snacks_dry", servingSize: "100g", calories: 277, protein: 1.8, carbs: 75, fat: 0.2, fiber: 6.7, isBangladeshi: true },
  { name: "Date Palm Jaggery (Khejur Gur)", category: "snacks_dry", servingSize: "15g", calories: 57, protein: 0.1, carbs: 14.7, fat: 0, fiber: 0, isBangladeshi: true },
  { name: "Date Palm Jaggery (Khejur Gur)", category: "snacks_dry", servingSize: "25g", calories: 96, protein: 0.1, carbs: 24.5, fat: 0, fiber: 0, isBangladeshi: true },
  { name: "Date Palm Jaggery (Khejur Gur)", category: "snacks_dry", servingSize: "50g", calories: 192, protein: 0.2, carbs: 49, fat: 0.1, fiber: 0, isBangladeshi: true },
  { name: "Date Palm Jaggery (Khejur Gur)", category: "snacks_dry", servingSize: "100g", calories: 383, protein: 0.4, carbs: 98, fat: 0.1, fiber: 0, isBangladeshi: true },
  { name: "Cashew Nuts (Kaju Badam)", category: "snacks_dry", servingSize: "15g", calories: 83, protein: 2.7, carbs: 4.5, fat: 6.6, fiber: 0.5, isBangladeshi: false },
  { name: "Cashew Nuts (Kaju Badam)", category: "snacks_dry", servingSize: "25g", calories: 138, protein: 4.5, carbs: 7.5, fat: 11, fiber: 0.8, isBangladeshi: false },
  { name: "Cashew Nuts (Kaju Badam)", category: "snacks_dry", servingSize: "50g", calories: 277, protein: 9, carbs: 15, fat: 22, fiber: 1.7, isBangladeshi: false },
  { name: "Cashew Nuts (Kaju Badam)", category: "snacks_dry", servingSize: "100g", calories: 553, protein: 18, carbs: 30, fat: 44, fiber: 3.3, isBangladeshi: false },
  { name: "Almonds (Kath Badam)", category: "snacks_dry", servingSize: "15g", calories: 87, protein: 3.2, carbs: 3.3, fat: 7.5, fiber: 1.9, isBangladeshi: false },
  { name: "Almonds (Kath Badam)", category: "snacks_dry", servingSize: "25g", calories: 145, protein: 5.3, carbs: 5.5, fat: 12.5, fiber: 3.1, isBangladeshi: false },
  { name: "Almonds (Kath Badam)", category: "snacks_dry", servingSize: "50g", calories: 290, protein: 10.5, carbs: 11, fat: 25, fiber: 6.3, isBangladeshi: false },
  { name: "Almonds (Kath Badam)", category: "snacks_dry", servingSize: "100g", calories: 579, protein: 21, carbs: 22, fat: 50, fiber: 12.5, isBangladeshi: false },
  { name: "Pumpkin Seeds (Kumro Bichi, roasted)", category: "snacks_dry", servingSize: "15g", calories: 84, protein: 4.5, carbs: 1.6, fat: 7.4, fiber: 0.9, isBangladeshi: true },
  { name: "Pumpkin Seeds (Kumro Bichi, roasted)", category: "snacks_dry", servingSize: "25g", calories: 140, protein: 7.5, carbs: 2.7, fat: 12.3, fiber: 1.5, isBangladeshi: true },
  { name: "Pumpkin Seeds (Kumro Bichi, roasted)", category: "snacks_dry", servingSize: "50g", calories: 280, protein: 15, carbs: 5.4, fat: 24.6, fiber: 3, isBangladeshi: true },
  { name: "Pumpkin Seeds (Kumro Bichi, roasted)", category: "snacks_dry", servingSize: "100g", calories: 560, protein: 30, carbs: 10.8, fat: 49.2, fiber: 6, isBangladeshi: true },
  { name: "Raisins (Kismis)", category: "snacks_dry", servingSize: "15g", calories: 45, protein: 0.5, carbs: 11.9, fat: 0.1, fiber: 0.6, isBangladeshi: true },
  { name: "Raisins (Kismis)", category: "snacks_dry", servingSize: "25g", calories: 75, protein: 0.8, carbs: 19.8, fat: 0.1, fiber: 1, isBangladeshi: true },
  { name: "Raisins (Kismis)", category: "snacks_dry", servingSize: "50g", calories: 150, protein: 1.6, carbs: 39.6, fat: 0.2, fiber: 2, isBangladeshi: true },
  { name: "Raisins (Kismis)", category: "snacks_dry", servingSize: "100g", calories: 299, protein: 3.1, carbs: 79.2, fat: 0.5, fiber: 3.7, isBangladeshi: true },
  { name: "Walnut (Akrot)", category: "snacks_dry", servingSize: "15g", calories: 98, protein: 2.3, carbs: 2.1, fat: 9.8, fiber: 1, isBangladeshi: false },
  { name: "Walnut (Akrot)", category: "snacks_dry", servingSize: "25g", calories: 163, protein: 3.8, carbs: 3.5, fat: 16.3, fiber: 1.7, isBangladeshi: false },
  { name: "Walnut (Akrot)", category: "snacks_dry", servingSize: "50g", calories: 327, protein: 7.6, carbs: 7, fat: 32.6, fiber: 3.4, isBangladeshi: false },
  { name: "Walnut (Akrot)", category: "snacks_dry", servingSize: "100g", calories: 654, protein: 15.2, carbs: 14, fat: 65.2, fiber: 6.7, isBangladeshi: false },
  { name: "Chia Seeds (raw)", category: "snacks_dry", servingSize: "15g", calories: 73, protein: 2.5, carbs: 6.3, fat: 4.6, fiber: 5.1, isBangladeshi: false },
  { name: "Chia Seeds (raw)", category: "snacks_dry", servingSize: "25g", calories: 122, protein: 4.1, carbs: 10.5, fat: 7.7, fiber: 8.6, isBangladeshi: false },
  { name: "Chia Seeds (raw)", category: "snacks_dry", servingSize: "50g", calories: 243, protein: 8.3, carbs: 21, fat: 15.4, fiber: 17.2, isBangladeshi: false },
  { name: "Chia Seeds (raw)", category: "snacks_dry", servingSize: "100g", calories: 486, protein: 16.5, carbs: 42, fat: 30.7, fiber: 34.4, isBangladeshi: false },

];
